project:
  type: website

website:
  title: "Reproducible Research Workflows in R"
  twitter-card:
    creator: "@Elliot_Gould_"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Slides
        menu: 
          - href: modules/introduction.qmd
            text: Introduction
          - href: modules/module_1.qmd
            text: "Project Organisation"
          - href: modules/module_2.qmd
            text: "Version Control"

execute:
  freeze: auto

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

