project:
  type: website

website:
  title: "Reproducible Research Workflows in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

execute:
  freeze: auto

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

